-- Enums domaine genealogique
CREATE TYPE gender_enum AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE person_status_enum AS ENUM ('CONFIRMED', 'PENDING', 'SUGGESTED_BY_AI');
CREATE TYPE privacy_enum AS ENUM ('PUBLIC', 'MEMBERS_ONLY', 'FAMILY_ONLY');
CREATE TYPE parent_role_enum AS ENUM ('FATHER', 'MOTHER');
CREATE TYPE parent_type_enum AS ENUM ('BIOLOGICAL', 'ADOPTIVE', 'STEP', 'FOSTER');
CREATE TYPE union_type_enum AS ENUM ('DOT', 'CIVIL', 'RELIGIOUS', 'TRADITIONAL', 'CONCUBINAGE');
CREATE TYPE end_reason_enum AS ENUM ('DEATH', 'DIVORCE', 'SEPARATION', 'ANNULMENT');
CREATE TYPE sibling_type_enum AS ENUM ('FULL', 'HALF_PATERNAL', 'HALF_MATERNAL', 'STEP');
CREATE TYPE relation_source_enum AS ENUM ('DECLARED', 'AI_SUGGESTED', 'IMPORTED', 'ADMIN');
CREATE TYPE ai_suggestion_status_enum AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED');
CREATE TYPE guard_type_enum AS ENUM ('GODPARENT', 'TUTOR', 'FOSTER_PARENT', 'CLAN_CHIEF');
